### PR TITLE
Add Icon Class 

### LINKED ISSUE #26: There Should Be An Icon Indicating Select Field
Like this icon at the end of the field:-
https://design.google.com/icons/#ic_arrow_drop_down

### PR DESCRIPTION
**Pull request by russell-tarpley**
Provides an Icon Class that is useable for selects by adding a div
containing the icon into the markup.
Tested in Opera, Safari, IE, Edge, Chrome, & FireFox

Fixes #26

### CODE REVIEW

**Comment by russell-tarpley** [comment]
The only issues I see in testing are:
- IE 11 - displays the native drop down underneath the icon (can be fixed by ms-expand)
- Firefox - displays a focus ring around the select control when focus is gained (can be fixed by moz-focusring)

@shaneog - can you give this pr a test?

**Comment by mebibou** [comment]
I am wondering, why having:

```
left: 0;
text-align: right;
width: 100%;
```

When you could juste do:

```
right: 0;
```

Wouldn't the result be the same?

**Comment by mebibou** [comment]
I created a fork with your files to test it:
http://codepen.io/mebibou/pen/MbgGBK

**Comment by mebibou** [comment]
Oh I just saw: could you have the icon get black (same color as the selected option) when an option is selected? it looks strange to still be gray. Something like this should work:

```
.mdl-selectfield__icon {
  ...
  .mdl-selectfield.is-dirty & {
    color: inherit;
  }
}
```

**Comment by russell-tarpley** [comment]
Made the updates you suggested @mebibou. Re-tested and haven't discovered any issues. My testing was in Opera, Safari, IE 11, Edge, Chrome, & FireFox

**Comment by russell-tarpley** [comment]
Have you had a chance to review my latest updates? @mebibou

**Pull request merged**
