### PR TITLE
Makes it easier to edit the styling

### PR DESCRIPTION
**Pull request by pndewit**
I found it pretty hard (need to override a lot of styles) just to make it less wide and remove the spacings. Noticed that these spacings were needed for the floating label version, so I moved the floating label stylings into floating label specific styles.

This is a raw version, I think a lot of positioning styles can still be removed (bottom: 0, top: 0, etc...).

Let me know what you think.

### CODE REVIEW

**Comment by mebibou** [comment]
Could you actually share a codepen or something on your actual use case? i.e. maybe showing how much you had to overwrite to get what you wanted? because I don't see what you are trying to do. FYI, I am trying to keep the code as close to the official mdl library as possible. You can see the correlation with the `textfield` here: https://github.com/google/material-design-lite/blob/mdl-1.x/src/textfield/_textfield.scss

**Comment by mebibou** [comment]
Just to make sure you understand: the `scss` file uses variables coming from the mdl library so that you could import it in your main `scss` file, after importing the mdl library, to eventually override the variables. Something like:
```scss
$selectfield-vertical-spacing: 20px;
@import "./node_modules/material-design-lite/src/material-design-lite.scss";
@import "./node_modules/mdl-selectfield/src/selectfield/selectfield.scss";
```

**Comment by pndewit** [comment]
Ah right, did not know that! I completely agree with you that it is best to keep it as close as possible to the MDL library. I wanted a label before the select field, so to the left of the select in a small sized container (+- 300px in total) without any paddings on top or bottom.

Codepen: http://codepen.io/anon/pen/bBmNLB
I added comments to show you what I needed to override.

I see I accidentally added a selector that was not supposed to be commited. Will remove that one!

Btw, I completely love your work. Thank you! Even if you decide not to proceed with these kind of changes!

**Comment by pndewit** [comment]
Oh and I am trying not to use SASS in my project and keep the amount of CSS overrides on top of MDL as low as possible. Besides, changing that variable will probably only make my life easier for the non-floating-label styled select box, right? The floating styled select box will then still need to be modified to look nice again.

**Comment by mebibou** [comment]
Well the variable I showed is just an example, there are many variables used in the component. Playing with all of them allows you to reduce the size of the component, it will change the position of the floating label, etc.
You have to understand that this component is designed to integrate with MDL, so when you use MDL and you want to have unified styles, you will override the sass variables instead of overriding every component, which you are trying to do. I am sure that if you try to do the same for a `textfield` (from the official MDL library), you will have the same issues, correct?

**Comment by mebibou** [comment]
Another thing, I tried using your version of the library in a codepen, this is how it looks: http://codepen.io/mebibou/pen/xRyYvV
It is clearly broken on Chrome, haven't tested on every other browser. If you make the scss simpler, fine, but it has to keep working as it was before (and cross-browser!), otherwise it would break for many people

**Comment by russell-tarpley** [comment]
I would imagine similar issues would occur with trying to override textfield as well. I agree with your direction @mebibou in keeping as close to mdl as possible giving that this was meant as an extension to fill a gap in the current MDL 1.x line. If you need to pursue a different direction @pndewit you might consider creating your own fork.

**Comment by pndewit** [comment]
@Rathxxx Sure, but I'd rather not of course.

@mebibou I understand what you are saying and I do agree with you. Like I said, I completely missed the argument that you were trying to keep your component as close to MDL as possible. I haven't encountered similar issues with other MDL components yet, but I just checked it out and you are right, the Textfield has the same kind of layout and will probably have the same issues.

About the codepen, strange that it looks broken! I am using Chrome, so at least that one should've been working. I must have deleted one positioning line too much, so I fixed the issue by reverting that deletion.

I'll have to either use SASS and see what I can do with the variables or live with the MDL design choices. Thanks for your help and time!

**Pull request closed without merging**
