### PR TITLE
Fix "sourceRoot" hardcoded to author's computer.

### PR DESCRIPTION
**Pull request by MatthewMerrill**
I believe this fixes the issue of source files not being mapped to the correct location when using the .map in chrome/firefox. This fix worked on my work laptop, but having a second person confirm it before merging would be appreciated.

All that should be changed is the "sourceRoot" key/val at the end of both .maps now use "../" to point at the main bower directory relative to current position rather than a path specific to the original author's computer.

### CODE REVIEW

**Comment by mebibou** [comment]
This won't solve the problem you mention, as those files are generated automatically with the gulp task: `gulp build`. Therefore the fix should be done in the task and not on the files that will be overridden with each release.

**Comment by MatthewMerrill** [comment]
Ahhh I see now. Thanks for the explanation.

**Comment by mebibou** [comment]
You don't have to close the PR, you can try by setting the `sourceRoot` option in the source maps generation in the gulp file, following: https://github.com/floridoo/gulp-sourcemaps#write-options

**Comment by mebibou** [comment]
I guess something like `sourcemaps.write('./', {includeContent: false, sourceRoot: '/src'})`

**Pull request closed without merging**
